# Generated by Django 5.1.7 on 2025-10-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
