# Generated by Django 5.1.7 on 2025-11-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
