# Generated by Django 5.1.7 on 2025-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='35363', max_length=11),
            preserve_default=False,
        ),
    ]
