# Generated by Django 5.1.7 on 2025-11-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contact_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
