# Generated by Django 5.1.7 on 2025-03-14 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
