# Generated by Django 5.1.7 on 2025-03-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
