# Generated by Django 5.1.7 on 2025-03-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
