# Generated by Django 5.1.7 on 2025-03-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0007_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='image',
        ),
    ]
