# Generated by Django 5.1.7 on 2025-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0009_flowerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerimage',
            name='image',
            field=models.ImageField(upload_to='flowers/images/'),
        ),
    ]
