# Generated by Django 5.1.7 on 2025-03-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0010_alter_flowerimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerimage',
            old_name='product',
            new_name='flower',
        ),
    ]
