# Generated by Django 5.1.7 on 2025-03-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_review'),
        ('order', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'flower')},
        ),
    ]
